### ISSUE TITLE
Add missed assets to Centrifuge

### ISSUE THREAD

**Issue by ImdioR** [dappforce/subid#130]
Hi guys!
**Merry Christmas!**
Centrifuge is here. We would like to ask you to add more assets on SubID.
Issue: Right now we are using SubID and not all assets are visible under Centrifuge wallet address.
Would be great if you could add all of them. Subscan already added them.
Subscan:
https://centrifuge.subscan.io/account/4dpEcgqJRyJK3J8Es6v8ZfVntV7c64Ysgcjd4hYwyGoFPWbg
SubID:  https://sub.id/4dpEcgqJRyJK3J8Es6v8ZfVntV7c64Ysgcjd4hYwyGoFPWbg
![image](https://github.com/dappforce/subid/assets/90972248/3e0058b9-076a-4b58-b04b-23f90d7f4ad3)
![image](https://github.com/dappforce/subid/assets/90972248/315afe76-b352-4387-a79c-bfd5418d6b99)

Description:

> - USDC
> - USDT
> - Frax (soon we have Onchain voting soon to add this tokens)
> - aUSD
> - GMLR
> - LTF (Custom token)

LTF - https://centrifuge.subscan.io/account/4dcSCJERtoQTyUbMa6SUmfJT2mcqePjZRoEyqQu8ugqJdtWJ?tab=transfer 

You can find supoprted assets here:  https://github.com/colorfulnotion/xcm-global-registry/blob/main/xcAssets/polkadot/polkadot_2031_xcAssets.json#L19

Please let me know if this is possible.
Thank you in advance.
Best.

**Comment by samchuk-vlad** [comment]
Fixed in this PR
https://github.com/dappforce/subid-api/pull/66
